name: tapeo_go
description: "TapeoGo: Tu pasaporte gastronómico por Sevilla. Proyecto Desarrollo de Aplicaciones Multiplataforma."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- PERSISTENCIA Y BACKEND ---
  supabase_flutter: ^2.0.0  # BD, Auth y Storage
  provider: ^6.1.1          # Gestión de estado con ChangeNotifier

  # --- MAPAS Y GEOLOCALIZACIÓN ---
  google_maps_flutter: ^2.5.3  # Mapa interactivo de Sevilla
  geolocator: ^10.1.0          # Validación de proximidad GPS en el check-in

  # --- MULTIMEDIA ---
  image_picker: ^1.0.7    # Selección de foto desde cámara o galería
  path_provider: ^2.1.5   # Rutas de archivos temporales en el dispositivo
  url_launcher: ^6.2.6    # Abrir enlaces externos

  # --- UTILIDADES ---
  intl: ^0.20.2         # Formateo de fechas en español
  confetti: ^0.7.0      # Animación de celebración al desbloquear medallas
  google_fonts: ^6.1.0  # Tipografía Poppins global
  shimmer: ^3.0.0       # Animación de esqueleto durante la carga de datos

  # --- HERRAMIENTAS UI/UX ---
  device_preview: ^1.3.1         # Vista previa en distintos tamaños de pantalla
  flutter_native_splash: ^2.4.7  # Pantalla de carga nativa

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1  # Generación automática del icono de la app

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/logoconletra.png
    - assets/images/logo_mapa.png
    - assets/images/logoapp.png
    - assets/images/logosplash.png

# --- ICONO DE LA APP ---
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logosplash.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/logosplash.png"
  

# --- SPLASH SCREEN NATIVA ---
flutter_native_splash:
  color: "#FFFFFF" 
  image: "assets/images/logoapp.png"

  android_12:
    image: "assets/images/logoapp.png"
    color: "#FFFFFF"

  android: true
  ios: true

